name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.5.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  faker: ^2.2.0
  file_picker: ^8.3.1
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_login: ^5.0.0
  flutter_supabase_chat_core:
    path: ../
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.3
  geolocator_android: 4.6.1
  http: ^1.3.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  supabase_flutter: ^2.8.3
  timeago: ^3.7.0
  duration: ^4.0.3
  mapbox_maps_flutter: ^2.6.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/