org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true

# Java interno de Android Studio
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr

# Esta línea es en caso de emergencia, colocar java 17 ahí en el peor de los casos, # ya que solo funciona si esta exactamente ahí
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17