// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuPIacYhb8pScY0H93CzOrb95X6XMXx6I',
    appId: '1:1041864147427:web:0328259b1f3820762460d6',
    messagingSenderId: '1041864147427',
    projectId: 'perdiem-ca028',
    authDomain: 'perdiem-ca028.firebaseapp.com',
    storageBucket: 'perdiem-ca028.firebasestorage.app',
    measurementId: 'G-QRKG05SSM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nIyFqzhkTefmJvXO4JCydBCl5RKoHSQ',
    appId: '1:1041864147427:android:92db00d0c328be802460d6',
    messagingSenderId: '1041864147427',
    projectId: 'perdiem-ca028',
    storageBucket: 'perdiem-ca028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWriQKkYnhy57adl_MdC0DzL2Bj_WclTg',
    appId: '1:1041864147427:ios:79286df420f154ae2460d6',
    messagingSenderId: '1041864147427',
    projectId: 'perdiem-ca028',
    storageBucket: 'perdiem-ca028.firebasestorage.app',
    iosBundleId: 'com.example',
  );
}
